import { FormEvent, useEffect, useState } from 'react';
import { Modal, Button, Row, Col, Form } from 'react-bootstrap';
import RequiredLabel from '../../../shared/components/RequiredLabel';
import { User, UserRequest } from '../models/UserModels';
const empty: UserRequest = { nombres: '',apellidos: '', nombreUsuario: '', correo: '', rolId: 0, password: '', activo: true };
export default function UserModal({ show, onHide, onSave, user, readonly }: { show: boolean; onHide: () => void; onSave: (p: UserRequest) => Promise<void>; user?: User | null; readonly?: boolean }) {
  const [form, setForm] = useState<UserRequest>(empty); const [validated, setValidated] = useState(false); const [saving, setSaving] = useState(false);
  useEffect(() => { if (show) setForm(user ? { nombres: user.nombres,apellidos: user.apellidos,  nombreUsuario: user.nombreUsuario, correo: user.correo, rol: user.rolId || '', activo: user.activo } : empty); setValidated(false); }, [show, user]);
  const submit = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); setValidated(true); if (!e.currentTarget.checkValidity()) return; setSaving(true); try { await onSave(form); onHide(); } finally { setSaving(false); } };
  const set = (k: keyof UserRequest, v: any) => setForm(prev => ({ ...prev, [k]: v }));
  return <Modal show={show} onHide={onHide} centered><Form noValidate className={validated ? 'was-validated' : ''} onSubmit={submit}><Modal.Header closeButton><Modal.Title>{readonly ? 'Detalle usuario' : user ? 'Editar usuario' : 'Nuevo usuario'}</Modal.Title></Modal.Header><Modal.Body><Row className="g-3">{user && <Col md={4}><Form.Label>Código</Form.Label><Form.Control value={user.id} disabled /></Col>}<Col md={user ? 8 : 12}><Form.Label><RequiredLabel>Nombre</RequiredLabel></Form.Label><Form.Control required disabled={readonly} value={form.nombre} onChange={e => set('nombre', e.target.value)} /></Col><Col md={6}><Form.Label><RequiredLabel>Usuario</RequiredLabel></Form.Label><Form.Control required disabled={readonly || !!user} value={form.usuario} onChange={e => set('usuario', e.target.value)} /></Col><Col md={6}><Form.Label><RequiredLabel>Correo</RequiredLabel></Form.Label><Form.Control required type="email" disabled={readonly} value={form.correo} onChange={e => set('correo', e.target.value)} /></Col><Col md={6}><Form.Label><RequiredLabel>Rol</RequiredLabel></Form.Label><Form.Control required disabled={readonly} value={form.rol || ''} onChange={e => set('rol', e.target.value)} /></Col>{!user && <Col md={6}><Form.Label><RequiredLabel>Contraseña</RequiredLabel></Form.Label><Form.Control required type="password" disabled={readonly} value={form.password || ''} onChange={e => set('password', e.target.value)} /></Col>}<Col md={6}><Form.Check type="switch" label="Activo" disabled={readonly} checked={!!form.activo} onChange={e => set('activo', e.target.checked)} /></Col></Row></Modal.Body><Modal.Footer><Button variant="secondary" onClick={onHide}>Cerrar</Button>{!readonly && <Button type="submit" disabled={saving}>{saving ? 'Guardando...' : 'Guardar'}</Button>}</Modal.Footer></Form></Modal>;
}
